import ResetPassword from '../Components/PasswordSucessModel';
import Portfolio from '../Screens/App/DashBoard/Portfolio';
import HundredPointForm from '../Screens/App/HundredPointForm';
import PreferenceSettings from '../Screens/App/Preference';
import CreateAccount from '../Screens/CreateAccount';

const Strings = {
  login: 'Login',
  email: 'Email',
  password: 'Password',
  create: 'Create an account',
  emailAlert: 'please enter your email',
  passwordAlert: 'please enter your password',
  passwordLength: 'Password should be atleast 5 characters long',
  invalidEmail: 'Invalid email address',
  loginSubHedding:
    'We happy to see you here again.Enter your email address and password',
  ForgotPassword: ' Forgot password?',
  forgotSubHedding:
    'Please enter your email address to receive a verification email',
  sign: 'Sign in',
  remember: 'Remember tha password?',
  next: 'Next',
  forgot: 'Forgot ',
  otp: 'OTP',
  verification: 'Verification',
  otpSubhedding: 'Enter 6 digit code sent to your email address and message',
  resendOtp: 'Resend OTP',
  changeNew: 'Change New',
  NewPasswordSubHedding:
    'Create your account.it takes less than a minute. Enter your details.',
  enterNewPassword: 'Enter new password',
  hey: 'Hey,',
  welcomeBack: 'Welcome back',
  didnotGetIt: `Didn't get it`,
  conformNewPassword: 'Conform new password',
  update: 'Update',
  newPasswordAlert: 'Please enter new password',
  conformPasswordAlert: 'Please conform new password',
  passwordNotMatch: 'New password & confirm password must be same ',
  passwordLength: 'password must be at least 6 characters long',
  passwordReset: 'Password Reset',
  successfully: 'Successfully',
  done: 'Done',
  createAn: 'Create an',
  account: 'Account',
  name: 'Name',
  companyName: 'Company name',
  signUp: 'Signup',
  chechboxHedding: 'I have by accept all ',
  termCoonditions: 'terms & Conditions',
  privacy: 'privacy',
  policy: 'policy',
  nameAlert: 'please enter your name',
  companyNameAlert: 'please enter company name',
  conformPassAlert: 'Please enter a conform password',
  phoneAlert: 'please enter phone number',
  hundredPoint: '100 Point',
  form: 'Form',
  hundredPointFormSubHedding:
    'Section 1 : Australian company identification procedure',
  generalInformation: 'General Information',
  fullName: 'Full name as registered by ASIC',
  tradingName: 'Trading name',
  acn: 'ACN',
  abn: 'ABN',
  registeredOfficeAddress: 'Registered Office Address',
  poBox: '(Po Box is NOT Acceptable)',
  street: 'Street ',
  suburb: 'Suburb ',
  state: 'State ',
  postCode: 'Postcode',
  mobileNumber: 'Mobile number',
  faxNumber: 'Fax number',
  alternateNumber: 'Alternate number',
  documentUpload: 'Document upload',
  hundredFormInformations:
    'Companies incorporated outside of Australia should complete the foreign companies identification form rather than form.',
  checkboxText1Hedding:
    'Proprietary (companies whose name ends with proprietary Ltd or Ltd; also known as private companies), proceed to 1.3',
  checkboxText2Hedding:
    'Public ( companies whose name does not      include the woprd Pty Or proprietary), proceed   to 1.4',
  directorsRequired:
    ' ( Required for all PRopritary Companies as per 1.2,not required for Public Companies) Provide the name of all directors.',
  fillGiven: 'Full given name (S)',
  enterName: 'Enter name',
  addMore: 'Add more',
  submit: 'Submit',
  checkboxWarning:
    'IF there are more directors,provide details on a separate sheet and tick the box ().',
  preferenceSetting: 'Preference Setting',
  paymentTerms: 'Payment Terms',
  paymentTermsText1: 'I would like to make payment after delivery',
  paymentTermsText2: 'I can make payment in advance',
  paymentTermsText3: 'Advance payment is mandatory',
  paymentTermsText4: 'Iam Flexible with payment',
  paymentTermsText5: 'I would like to decide at the time of deal',
  paymentTermsText6: 'I can accept payment after delivery',
  primaryContactPerson: 'Primary Contact Person',
  contactNumber: 'Contact number',
  secondaryContactPerson: 'Secondary Contact Person',
  otherContactNumberPerson: 'Other Contact Person',
  skip: 'Skip',
  tradeexculusionlist: 'Trade Exclusion List',
  retailers: 'Retailers',
  aggregator: 'Aggregator',
  ap: 'AP',
  energy: 'Energy',
  trade: 'Trade',
  marketIsDown: 'Market Is Down',
  inThePast: 'In the past 24 hours',
  trending: 'Trending',
  traderList: 'Trader List',
  sell: 'Sell',
  buy: 'Buy',
  setting: 'Setting',
  accountSetting: 'Account Setting',
  profileSetting: 'Profile Setting',
  ResetPassword: 'Reset Password',
  logout: 'Logout',
  deleteAccount: 'Delete Account',
  energyTradingSettings: 'Energy Trading Setting',
  energyTrading: 'Energy Trading',
  privacyPolicy: 'Privacy Policy',
  termsOfUse: 'Terms of Use',
  faqs: `FAQ'S`,
  permissions: 'Permissions',
  help: 'Help',
  senfFeedback: 'Send Feedback',
  checkForUpdate: 'Check for Updates',
  needHelp: 'Need Help?',
  notification: 'Notifications',
  today: 'Today',
  hundredPointForm: '100 Points Form',
  profile: 'Profile',
  userName: 'Prageet Makreri',
  userId: 'userId 80008',
  emailId: 'prageet.digipanda.com',
  add: 'Add',
  balance: '$0.00',
  refer: 'Refer',
  invoice: 'Invoice',
  accountDetails: 'Account Details',
  bankDetails: 'Bank Details',
  invite: 'Invite',
  myPortfolio: 'My Portfolio',
  live: 'Live',
  closed: 'Closed',
  Portfolio: 'Portfolio',
  invest: '$8.8',
  investment: 'Investment',
  return: 'Return',
  return: '-$8.8',
  todayReturn: `Today's return`,
  todayReturnAmount: '$0.00',
  returnText: 'Return',
  closedTrade: 'Closed Trades',
  liveTrade: 'Live Trades',
  tradeCompany: 'Trade Company',
  unit:'(56 AUD/Unit)',
  totalAmount: '$21,000 ',
  priceAmount:'$200/100U US $200.00',
  profitAmount: '+8.88%',
  price:"Price",
  sellAmount:'$8,808.08',
  plus:"+",
  minus:"-",
  quantity:"Quantity",
  sellquantity:"100",
  youPut:"You put",
  youPuAmount:'$6.00',
  youGet:'You get',
  youGetAmount:'$12,00',
  orderBook:"Order Book",
  advancedOptions:"Advanced Options",
  advancePayment:'Advance payment',
  deliveryAfterPayment:"Delivery after payment",
  listALimitedOrders:"List a limited orders",
  autoCancelation:'Auto cancellation',
  availableBalance:"Available balance",
  knowMore:"Know more",
  availableBalanceAmount:'$100.00',
  swipeForSell:"Swipe for Sell",
  to:"to",
  sent:"Sent",
  groupName:"Group Name",
  enterprisePvtLtd:"Enterprise Pvt.Ltd",
  view:"View",
  one:"1",
  marketPrise:"Market Price (200 AUD/Unit",
  prefrence:"Prefrences",
  DeliveryAfterPayment:"Delivery After Payment,",
  AdvancePayment:"Advance Payment",
  note:"Note",
  noteText:"I want to buy today you delivery me on 30 Apr,2024",
  date:"jul, 2024 08:08PM",
  sendC:"Send C",
  counter:"Counter",
  markketPrice:"Markket Price (200 AUD/Unit)",  
  orderId:"Order ID: 855693066",
  dateLive:"Apr 09,2024 16:35",
  settled:"Settled",
  limit:"Limit",
  orderType:"Order Type",
  quantity:"Quantity",
  price:'Price',
  taxesServices:"Taxes & services",
  TotalAmount:'Total Amount',
  confirmPassword:"Confirm password"

  



  

};

export default Strings;
